- name: prepare PostgreSQL for SonarQube
  ansible.builtin.apt:
    name:
      - acl
      - python3-psycopg2
    state: present
    update_cache: true

- name: Install PostgreSQL
  ansible.builtin.apt:
    name: "{{ postgresql_packages }}"
    state: present
    update_cache: true

- name: Ensure PostgreSQL started
  ansible.builtin.service:
    name: "{{ postgresql_service }}"
    state: started
    enabled: true

# Требуется коллекция: ansible-galaxy collection install community.postgresql
- name: Create sonar DB user
  community.postgresql.postgresql_user:
    name: "{{ postgres_sonar_user }}"
    password: "{{ postgres_sonar_password }}"
    encrypted: true
  become: true
  become_user: postgres


- name: Create sonarqube database
  community.postgresql.postgresql_db:
    name: "{{ postgres_sonar_db }}"
    owner: "{{ postgres_sonar_user }}"
  become: true
  become_user: postgres